version: '3.7'

services:

  web:
    container_name: 'aspnetcoreapp'
    image: 'aspnetcoreapp'
    build:
      context: .
      dockerfile: aspnet.dockerfile
    ports:
      - "5000:80"
    depends_on:
      - "postgres"
    networks:
      - aspnetcoreapp-network
  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      # change this for a "real" app!
      POSTGRES_PASSWORD: admin
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge